version: "3"
services:
  app:
    container_name: youknow
    build:
      context: ./typescript_app
      dockerfile: Dockerfile
    restart: unless-stopped
    #ports:
    #  - "8080:3000"  # Maps host port 8080 to container port 3000 for local debug

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      LANG: $LANG

  app1:
    container_name: youknow_validations

    build:
      context: ./youknow_validations
      dockerfile: Dockerfile
    restart: unless-stopped

  app2:
    container_name: youknow_ytscraper

    build:
      context: ./youknow_ytscraper
      dockerfile: Dockerfile
    restart: unless-stopped

networks:
  default:
    external: true
    name: npm

volumes:
  mysql_data:
