name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Production:
    name: Deploy to Homelab
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Cloudflared SSH Run Remote Commands
        uses: npgy/cloudflared-ssh-action@v2.0
        with:
          SSH_HOST: ${{ vars.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
          commands: cd /root/youknow; git reset--hard; git checkout main; git pull origin main; docker stop youknow; docker rm youknow; docker build -t youknow_nextjs .; docker run --detach --network tunnel --name youknow youknow_nextjs